### ISSUE TITLE
First tab regularly does not retain address.

### ISSUE THREAD

**Issue by wolfbeast** [JustOff/lull-the-tabs#5] opened 2018-04-10 12:50 UTC
The first tab on the tab bar regularly does not retain its address, and loads the home page instead when activated, even if the stored state has the proper title and favicon and everything.

I don't have exact steps to reproduce but it happens regularly enough to know it must be a flaw somewhere in this extension. This never happened with bartab.

**Comment by JustOff** [comment] 2018-04-10 13:06
I've never seen this myself. Do you have any other tab/session add-ons installed?

As a guess, this could be somehow related to [Pale-Moon#1640](https://github.com/MoonchildProductions/Pale-Moon/pull/1640) (and should be fixed by it, if it's so).

**Comment by JustOff** [comment] 2018-04-10 15:59
I took a closer look to this, but unfortunately I still can't reproduce the problem or figure out how exactly [Pale-Moon#1640](https://github.com/MoonchildProductions/Pale-Moon/pull/1640) can affect LTT to cause such confusion. However, at the moment that issue remains the main suspect.

Meanwhile, could you please clarify your browser startup settings (General->Startup), where your home page points (local file, chrome url or remote site) and which LTT settings differ from defaults in your configuration?

**Comment by wolfbeast** [comment] 2018-04-10 17:44
Session: restore windows and tabs from last time
Home page: http://start.palemoon.org/

Changed prefs:
```
extensions.lull-the-tabs.autoUnload;true
extensions.lull-the-tabs.exceptionList;onlinepizza.se;docs.google.com;www.cloudflare.com;forum.palemoon.org;archive.org;192.168.0.10
extensions.lull-the-tabs.importBarTab;false
extensions.lull-the-tabs.leftIsNearest;true
extensions.lull-the-tabs.showButton;false
```

**Comment by JustOff** [comment] 2018-04-17 15:47
Please report if this happens again on Pale Moon `27.9.0`.

**Comment by wolfbeast** [comment] 2018-04-23 10:56
I haven't seen this happening anymore in 27.9.0 so the sync loading of the session seems to have fixed this.

**Comment by JustOff** [comment] 2018-04-23 11:00
Thanks for the confirmation. Let's hope it did it.

**Closed by JustOff** 2018-04-23 11:00 UTC
